### ISSUE TITLE
ValueError: Values other than "rc" for the "coordinates" argument to skimage.measure.regionprops are no longer supported.

### ISSUE THREAD

**Issue by maryloooh** [giswqs/lidar#7] opened 2020-01-27 05:13 UTC
* lidar version: 
* Python version: 3.7
* Operating System: Windows 10

### Description

I tried running the example.py with the dem.tif but got the following error:

```
# identify the sample data directory of the package
#package_name = 'lidar'
#data_dir = pkg_resources.resource_filename(package_name, 'data/')
data_dir = 'lidar'

# use the sample dem. Change it to your own dem if needed
in_dem = os.path.join(data_dir, 'dem.tif')
# set output directory. By default, use the temp directory under user's home directory
out_dir = os.path.join(os.path.expanduser("~"), "temp")

# parameters for identifying sinks and delineating nested depressions
min_size = 1000      # minimum number of pixels as a depression
min_depth = 0.5      # minimum depth as a depression
interval = 0.3       # slicing interval for the level-set method
bool_shp = True     # output shapefiles for each individual level

# extracting sinks based on user-defined minimum depression size
out_dem = os.path.join(out_dir, "median.tif")
in_dem = lidar.MedianFilter(in_dem, kernel_size=3, out_file=out_dem)
sink_path = lidar.ExtractSinks(in_dem, min_size, out_dir)
dep_id_path, dep_level_path = lidar.DelineateDepressions(sink_path, min_size, min_depth, interval, out_dir, bool_shp)

print('Results are saved in: {}'.format(out_dir))

Median filtering ...
Run time: 0.0290 seconds
Saving dem ...
Loading data ...
min = 379.70, max = 410.72, no_data = -3.402823e+38, cell_size = 1.0
Depression filling ...
Saving filled dem ...
Region grouping ...
Computing properties ...

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-d90bdedee5d6> in <module>
     18 out_dem = os.path.join(out_dir, "median.tif")
     19 in_dem = lidar.MedianFilter(in_dem, kernel_size=3, out_file=out_dem)
---> 20 sink_path = lidar.ExtractSinks(in_dem, min_size, out_dir)
     21 dep_id_path, dep_level_path = lidar.DelineateDepressions(sink_path, min_size, min_depth, interval, out_dir, bool_shp)
     22 

~\Anaconda3\envs\py37\lib\site-packages\lidar\filling.py in ExtractSinks(in_dem, min_size, out_dir)
    178 
    179     print("Computing properties ...")
--> 180     objects = measure.regionprops(label_objects, dem, coordinates='xy')
    181     dep_list = get_dep_props(objects, cell_size)
    182     write_dep_csv(dep_list, out_csv_file)

~\Anaconda3\envs\py37\lib\site-packages\skimage\measure\_regionprops.py in regionprops(label_image, intensity_image, cache, coordinates)
    855                    'stop using the "coordinates" argument, or use skimage '
    856                    'version 0.15.x or earlier.')
--> 857             raise ValueError(msg)
    858 
    859     regions = []

ValueError: Values other than "rc" for the "coordinates" argument to skimage.measure.regionprops are no longer supported. You should update your code to use "rc" coordinates and stop using the "coordinates" argument, or use skimage version 0.15.x or earlier.

**Comment by giswqs** [comment] 2020-01-27 13:04
This issue seems to be caused by the version of the scikit-image package. I will look into that.

**Comment by maryloooh** [comment] 2020-01-27 13:06
Thank you very much!

**Comment by giswqs** [comment] 2020-01-27 17:07
The issue has been fixed. Please update the package using `pip install -U lidar`. It should be working now.

**Comment by maryloooh** [comment] 2020-01-27 20:23
Thank you very much for the quick response and fix! I'll try it out.

So I need to download the new version first then type in the update code in
anaconda?

**Comment by giswqs** [comment] 2020-01-27 20:42
Activate your conda environment and then use pip install, such as 
```
conda activate py37
pip install -U lidar
```

**Comment by maryloooh** [comment] 2020-01-27 21:37
Awesome! It worked :)

Thank you so much!

**Comment by giswqs** [comment] 2020-01-27 21:39
@maryloooh Great! I am closing this issue. Feel free to open a new issue if you run into any problems.

**Closed by giswqs** 2020-01-27 21:39 UTC

**Comment by maryloooh** [comment] 2020-01-27 21:41
Thanks, will do!
Now going to try to run it with my own data, so we'll see how that is going
to work.. fingers crossed!
